apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  # type default is ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    # It tells what port this deployment manages
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # match to selector
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

